### ISSUE TITLE
MAAS docs link on docs.staging.ubuntu.com doesn't link to staging

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/docs.ubuntu.com#139]
## Summary

MAAS docs link on docs.staging.ubuntu.com doesn't link to staging. This seems to have changed with an update changing docs from https://docs.ubuntu.com/maas/ to https://docs.maas.io/.

## Process

Run _Project deploy-to-docs.staging.ubuntu.com_
On completion, open https://docs.staging.ubuntu.com/ and click on the Read the MAAS documentation  link. 

## Current and expected result

You're redirected to https://docs.maas.io/2.3/en/ rather than https://docs.staging.ubuntu.com/maas/2.3/en/

## Screenshot

![image](https://user-images.githubusercontent.com/7047542/36314460-dbf98756-132c-11e8-8041-62c57f0ac57a.png)

**Comment by tbille** [comment]
There are no more maas staging docs.
