### ISSUE TITLE
400 error from “Style Guide” link on “Style Guide” page

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/docs.ubuntu.com#158]
1\. Go to [the Canonical Documentation Style Guide page](https://docs.ubuntu.com/styleguide/en).
2\. Follow the “Style Guide” link in the corner.

What happens: “[Page not found (404)](https://docs.ubuntu.com/styleguide/)”

What should happen: The text should not be a link. The Style Guide is a single page, so you’re guaranteed to be on the page already.

**Comment by tbille** [comment]
Now we get a `500`

**Comment by matthewpaulthomas** [comment]
FWIW, the “[Snap Store Proxy documentation](https://docs.ubuntu.com/snap-store-proxy/en/)” page is also on docs.ubuntu.com, and has an equivalent link in its nav, but that one redirects rather than returning an error.
