### ISSUE TITLE
Images missing from Simple+Advanced production model pages

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/docs.ubuntu.com#160]
1\. Go to the “[Simple production model](https://docs.ubuntu.com/core/en/guides/go-to-production/simple)” page.
2\. Go to the “[Advanced production model](https://docs.ubuntu.com/core/en/guides/go-to-production/advanced)” page.

What you see: Broken image links.

The pages try to embed these images, which return 404 errors:
https://docs.ubuntu.com/static/media/core/production-model-simple.png
https://docs.ubuntu.com/static/media/core/production-model-rich.png

**Comment by anthonydillon** [comment]
These images are loading correctly now.
