### ISSUE TITLE
Page contents start below viewport and appear under sidebar

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/docs.ubuntu.com#206]
1\. Go to [docs.jujucharms.com/2.5/en/clouds-aws](https://docs.jujucharms.com/2.5/en/clouds-aws).
2\. Change to any zoom level lower than 100%.
3\. Change to 100% zoom or higher.

What happens:

2\. The page appears correctly.

3\. The page text and illustrations are scrolled off the bottom of the page, and slide under the left sidebar.
![docs jujucharms com-scrolling](https://user-images.githubusercontent.com/19801137/52795812-7dfe5f80-306a-11e9-8032-b8e0ff82381f.gif)

This may be related to #188.

**Comment by pmahnke** [comment]
Closing, these are the old github based docs.  Juju now uses discourse based docs.
