### ISSUE TITLE
“Search Style Guide docs” does nothing useful

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/docs.ubuntu.com#213]
1\. Go to [the Canonical Documentation Style Guide page](https://docs.ubuntu.com/styleguide/en).
2\. In the “Search Style Guide docs” field, enter anything that you know is present in the guide, for example “[hyperlinks](https://docs.ubuntu.com/search?q=hyperlinks&domain=docs.ubuntu.com%2Fstyleguide)” or “[headlines](https://docs.ubuntu.com/search?q=headlines&domain=docs.ubuntu.com%2Fstyleguide)”.

What happens:
- No matter what you search for, the search returns exactly one result, “[| Style Guide](https://docs.ubuntu.com/styleguide/en)”.
- Following that link does not get you any closer to the relevant section, it just goes to the top of the original page.

What should happen:
- A site that consists of a single page should not have a search field.

This is the sequel to #159.

**Comment by pmahnke** [comment]
The search has been removed, closing.

**Comment by matthewpaulthomas** [comment]
Unfortunately the issue still exists as described.

![image](https://user-images.githubusercontent.com/19801137/81289665-b4087480-905e-11ea-8eaa-eabf10ae432f.png)

**Comment by carkod** [comment]
@SirSamTumless @pmahnke these changes need to be done on https://github.com/canonical-web-and-design/praecepta, is this still active?
