### ISSUE TITLE
Going to existing page without "/" in link fails

### ISSUE THREAD

**Issue by anonymouse64** [canonical-web-and-design/docs.ubuntu.com#215]
## Summary

This link (verbatim) should work: https://docs.ubuntu.com/core/en/build-store
However it only works if I add a "/" at the end: https://docs.ubuntu.com/core/en/build-store/

## Process

Go to https://docs.ubuntu.com/core/en/build-store

## Current and expected result

Got a 404 page 

## Screenshot

![Screenshot from 2019-05-09 11-01-08](https://user-images.githubusercontent.com/6006573/57468304-d009e800-7249-11e9-9011-a2334db7a791.png)

**Comment by carkod** [comment]
It should be redirecting to https://ubuntu.com/core/docs/store-overview now

**Comment by anonymouse64** [comment]
Yep looks good to me thanks for fixing this
