### ISSUE TITLE
Can not access unity api doc any more on developer.ubuntu.com

### ISSUE THREAD

**Issue by khurshid-alam** [canonical-web-and-design/docs.ubuntu.com#217]
After new design of the website I can not access any of the api doc for indicators and messaging menu. For example,

https://developer.ubuntu.com/api/devel/ubuntu-13.10/python/MessagingMenu-1.0#MessagingMenu.Message

now gives 404. :/

I have also asked the same in ubuntu-doc mailing list.

**Comment by pmahnke** [comment]
Is this what you are looking for? https://docs.ubuntu.com/phone/en/

**Comment by khurshid-alam** [comment]
Not at all. Phone api is not same as desktop api and it has nothing to do with desktop api. The readme describe how to run the server inside docker and view the html pages. You can check it yourself. The fork of libmesseging-menu, ayatana-messeging-menu is already in debian and the api doc should be similar to [that.](https://lazka.github.io/pgi-docs/#MessagingMenu-1.0/classes/App.html)

**Comment by pmahnke** [comment]
@khurshid-alam sorry, I actually replied to the wrong issue.

I have been looking and I think the old docs simply formatted documentation inside the code.

I will keep looking to see if we have a copy someplace.

**Comment by pmahnke** [comment]
We can't seem to find the content of the docs.  I believe it might have been built from the code.  We are going to close this issue as we do not have the resource to find and fix.
