### ISSUE TITLE
https://docs.ubuntu.com/phone/ still exists

### ISSUE THREAD

**Issue by setharnold** [canonical-web-and-design/docs.ubuntu.com#224]
Hello; https://docs.ubuntu.com/phone/en/ still exists and still documents our phone offering, which is no longer available. Probably we can pull all this down.

Thanks

**Comment by tbille** [comment]
This project is still being used and read by external users. If there is specific content that should be removed that would show phone offerings can you reopen the issue with links please?

Thanks
