### ISSUE TITLE
Juju docs URL is outdated

### ISSUE THREAD

**Issue by pmatulis** [canonical-web-and-design/docs.ubuntu.com#228]
The Juju link on docs.ubuntu.com is:

https://jujucharms.com/docs/stable/getting-started

Although this redirects to prevent a 404, it should be updated to:

https://jaas.ai/docs

I wouldn't hardcode the getting-started page as this may change in the future. The URL just above redirects automatically at this time to getting-started.

**Comment by anthonydillon** [comment]
It redirects successfully to https://jaas.ai/docs/getting-started-with-juju for me. Do you experence something else?

**Comment by pmatulis** [comment]
Yes, I tried to be clear on this. It does redirect. But two things:

1. We should use the correct URL.
2. We should not hardcode getting-started in docs.ubuntu.com as this may change. This redirect can be managed at the Juju docs repo level right?

**Comment by anthonydillon** [comment]
Ah I see, just what's to gage the priority of this change. Which seems low. Even so, I have committed a range of updates to links on that page, including JAAS.
