### ISSUE TITLE
Add file-a-bug and edit-this-page links

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/docs.ubuntu.com#24]
In either the left or right sidebar, or in the footer, there should be links to file a bug and edit ths page, which take you to github. Is there a way to include the page you came from in the issue description? I think there should be...

**Comment by pmahnke** [comment]
resin.io does this nicely... well, I like the words, the link and button aren't quite right...

![image](https://cloud.githubusercontent.com/assets/441217/22327155/b0ac6a32-e3ad-11e6-9254-7fff501f0de7.png)

**Comment by tbille** [comment]
We are moving to discourse docs format. This issue won't be relevant anymore.
