### ISSUE TITLE
OpenStack uses the wrong letter case on the frontpage

### ISSUE THREAD

**Issue by pmatulis** [canonical-web-and-design/docs.ubuntu.com#248]
OpenStack is written in the wrong case in the Juju "box". It shows as "openstack" when it should be "OpenStack".

![image](https://user-images.githubusercontent.com/6303808/86676369-87be9500-bfc8-11ea-87a7-1dde487ea788.png)

**Comment by pmahnke** [comment]
Also remove conjure-up docs
