### ISSUE TITLE
Ubuntu Core docs search 404s

### ISSUE THREAD

**Issue by doismellburning** [canonical-web-and-design/docs.ubuntu.com#254]
## Summary

Trying to search core docs gives me an nginx 404

## Process

* Visit http://docs.ubuntu.com/core/
* (Get redirected to https://core.docs.ubuntu.com/en/)
* Enter a search term in the bar on the top right (e.g. test)
* Be sent to https://core.docs.ubuntu.com/search?q=test&domain=docs.ubuntu.com%2Fcore which is an nginx 404 page

## Current and expected result

I get a 404; I would like some search results

**Comment by carkod** [comment]
Superseeded by https://github.com/canonical-web-and-design/web-squad/issues/3164

**Comment by doismellburning** [comment]
I can't see the superseding issue because it's in a private repo, but it looks like https://github.com/canonical-web-and-design/ubuntu-core-docs/pull/122 has fixed it anyway so thanks

Should future issues be filed against docs.ubuntu.com or ubuntu-core-docs? I'm guessing the latter for core-specific issues?
