### ISSUE TITLE
Snap store proxy docs not current

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/docs.ubuntu.com#305]
## Summary

The published snap-store proxy docs seem to be behind the current contents of the docs repo

## Process

Compare https://github.com/canonical-ols/snapstore-snap-docs with content at https://docs.ubuntu.com/snap-store-proxy/en/

## Current and expected result

Site shows old version of docs (the footer is labelled 2018...)
Actual docs repo has some minor but important changes.

**Comment by sowasred2012** [comment]
@evilnick it looks as though this has been updated - are you happy for me to close this?
