### ISSUE TITLE
Search improvements

### ISSUE THREAD

**Issue by pmatulis** [canonical-web-and-design/docs.ubuntu.com#61]
Issue #11 was closed without implementing the bulk of the requirements for the search facility:

- [ ] Default technology and software version is based on where the reader initiates the search from
- [ ] Include an advanced search dialog that allows for the selection of multiple technologies and software versions (for each)
- [ ] Each search result must be clearly associated with a technology and software version. It seems to me that results should somehow be organized by technology and software version
- [ ] Make better use of whitespace

Be mindful that documentation may one day be offered in multiple languages. Therefore, the search facility should be ready to accommodate the ability to query by language.

@evilnick 
@degville 
@matthewhelmke

**Comment by tbille** [comment]
Search is removed from the site.
