### ISSUE TITLE
Make each of the documentation sets a standalone site

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/docs.ubuntu.com#88]
For the Kubernetes deployment system, each set of documentation will be built as a separate Docker image, which can then be deployed at its own subdomain or at a subpath of docs.ubuntu.com.

This means that it no longer makes sense to consider the `docs.ubuntu.com` app to be the central place that serves all documentation.

So we need:

- A way to serve each set of documentation locally, independently
- A place to keep the Dockerfile for building each set of documentation

These could either live inside each documentation set, or in separate repositories dedicated to the building and releasing of a specific set of documentation, or in this repository. I'm not sure which is best right now, but it needs to be decided.

**Comment by nottrobin** [comment]
Splitting up the documentation sets in this way and deploying them to Kubernetes makes it trivial to provide #13, as hosting each documentation set at a subdomain or subpath will be as simple as changing a configuration option.

**Comment by nottrobin** [comment]
The decision here is to make each set of documentation contain its own `Dockerfile` and `./run` script such that it can be easily run for local development and packaged for release to production all from within each documentation set's repository.

For cases like vanilla-framework where the docs live in a sub-folder of the main project, the `docs/` subdirectory should contain the `Dockerfile`, and the central project's `./run` script should be extended to allow you to build and serve docs as well / instead.

**Comment by tbille** [comment]
Not current model anymore. Closing this issue.
